# Generated by Django 5.1.1 on 2024-09-28 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bazar_app', '0002_rename_customer_userprofile_remove_cartitem_cart_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='video_link',
            field=models.URLField(blank=True),
        ),
    ]
