# Generated by Django 5.1.1 on 2024-09-29 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bazar_app', '0003_product_video_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
